Revert "feat: reworked fossa action in github workflows"
This reverts commit e70f14f79afd7f7bbb4f78b8c18b1b1faccf1852.

diff --git a/.github/workflows/ci-lite.yaml b/.github/workflows/ci-lite.yaml
--- a/.github/workflows/ci-lite.yaml
+++ b/.github/workflows/ci-lite.yaml
@@ -87,22 +87,25 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
-      - name: run fossa analyze and create report
-        id: fossa
-        continue-on-error: true
-        uses: fossas/fossa-action@8dea2e348349fad66e838ce0b365b044c6bf2011 # v2.0.0
-        with:
-          api-key: ${{ secrets.FOSSA_API_KEY }}
-          debug: true
-          generate-report: text
-          run-tests: true
-      - name: write THIRDPARTY report to file
-        run: echo '${{ steps.fossa.outputs.report }}' > /tmp/THIRDPARTY
+      - name: run fossa anlyze and create report
+        run: |
+          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
+          fossa analyze --debug
+          fossa report attribution --format text > /tmp/THIRDPARTY
+        env:
+          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
       - name: upload THIRDPARTY file
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: THIRDPARTY
           path: /tmp/THIRDPARTY
+      - name: run fossa test
+        run: |
+          if ! fossa test --debug; then
+            echo "::warning::FOSSA compliance test failed. Review issues above."
+          fi
+        env:
+          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
 
   build_action:
     runs-on: ubuntu-latest
